language: java

dist: xenial

branches:
  except:
      #- /^(?i:feature)-.*$/
      #- /^(?i:release)-.*$/

jdk:
  - oraclejdk8
  - openjdk11
  - openjdk-ea

install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -U -V -q
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

notifications:
    email:
        on_success: never
        on_failure: never
    slack:
        on_failure: change
        on_success: change
        rooms:
            - openbase-org:vGz7LO4CvGoGMneYkEm3ON7E#build
            #- openbase-org:vGz7LO4CvGoGMneYkEm3ON7E#bco-eveson

deploy:
  - provider: script
    script: .travis/deploy.sh
    on:
        repo: openbase/bco.eveson
        branch: master
        jdk: oraclejdk8
  - provider: script
    script: .travis/deploy.sh
    on:
        repo: openbase/bco.eveson
        tags: true
        jdk: oraclejdk8

after_deploy:
   - |
       if [[ ($TRAVIS_BRANCH == master) &&
             ($TRAVIS_PULL_REQUEST == false) &&
             ( (! $TRAVIS_JOB_NUMBER == *.*) || ($TRAVIS_JOB_NUMBER == *.1) ) ]] ; then
         curl -LO https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh

         # trigger upstream projects
         #sh trigger-travis.sh openbase bco.manager $TRAVIS_ACCESS_TOKEN
       fi
